### ISSUE TITLE
Fatal Errors

### ISSUE THREAD

**Issue by grendelmintcake** [ElliotGarbus/ChaseBlissEditor#1] opened 2021-04-15 19:59 UTC
Getting a lot of 'Failed to execute script main' errors when using this with windows 10.  Uploaded a screengrab, though I'm sure you get the idea.  I'm seeing this when attempting to either Create or Recall Initial Patch.

Also, clicking 'Send to Brothers' appears to affect no changes on the pedal.  Something MIDI related, maybe?

![BrothersChaseBlissErrorExecuteScript](https://user-images.githubusercontent.com/82612319/114930657-2e27a880-9e2d-11eb-9b96-628cbd7692d5.JPG)

**Comment by ElliotGarbus** [comment] 2021-04-15 22:11
2 interesting issues... 
On the failed to execute script issue.  There seems to be a failure when creating to storing the initial patch.  I'm guessing that a file has been corrupted.  

Click on the open file button (in the upper left), In the dialog select and delete the file init_patch_Brothers.cbp 
Then try create  and see if the problem is resolved.

If the problem is not resolved, you can help me by finding and posting the logfile that gets created when this problem occurs.  The file will be located at: C:\Users\your-user-name-here\\.kivy\logs
Please post the log file.

A log file with no errors looks like:

[INFO   ] Logger: Record log in C:\Users\ellio\.kivy\logs\kivy_21-04-15_7.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "C:\Program Files (x86)\Chase Bliss Editor\kivy\__init__.pyc"
[INFO   ] Python: v3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
[INFO   ] Python: Interpreter at "C:\Program Files (x86)\Chase Bliss Editor\Chase Bliss Editor.exe"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.6.0 NVIDIA 461.37'>
[INFO   ] GL: OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] GL: OpenGL renderer <b'GeForce RTX 2060/PCIe/SSE2'>
[INFO   ] GL: OpenGL parsed version: 4, 6
[INFO   ] GL: Shading version <b'4.60 NVIDIA'>
[INFO   ] GL: Texture max size <32768>
[INFO   ] GL: Texture max units <32>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[INFO   ] GL: NPOT texture support is available
[INFO   ] GL: Unpack subimage support is available
[WARNING] Both Window.minimum_width and Window.minimum_height must be bigger than 0 for the size restriction to take effect.
[INFO   ] Base: Start application main loop
[INFO   ] WindowSDL: exiting mainloop and closing.
[INFO   ] Base: Leaving application in progress...

**Comment by ElliotGarbus** [comment] 2021-04-15 22:14
On to the MIDI Issue:
Save to Brother should send the current settings on the screen to the pedal.  If the settings on the pedal and on the screen are similar you may not hear the difference.  Note that when you change the settings on the screen, the settings on the pedal are changing real-time.   To ensure "Send to Brothers" is working as expected, Set the knobs on the screen.  The twist the knobs on the pedal to create a much different sound, the click send to brothers to hear the sound that is set on the screen.

Assuming you should be hearing the difference and are not, there could be an issue with the midi devices you are using or the way they are connected. 

How are you connecting the pedal to the computer?  Please include the devices and the cable types (TS or TRS).

**Comment by grendelmintcake** [comment] 2021-04-16 12:32
> 2 interesting issues...
> On the failed to execute script issue. There seems to be a failure when creating to storing the initial patch. I'm guessing that a file has been corrupted.
> 
> Click on the open file button (in the upper left), In the dialog select and delete the file init_patch_Brothers.cbp
> Then try create and see if the problem is resolved.
> 
> If the problem is not resolved, you can help me by finding and posting the logfile that gets created when this problem occurs. The file will be located at: C:\Users\your-user-name-here\.kivy\logs
> Please post the log file.
> 
> A log file with no errors looks like:
> 
> [INFO ] Logger: Record log in C:\Users\ellio.kivy\logs\kivy_21-04-15_7.txt
> [INFO ] Kivy: v1.11.1
> [INFO ] Kivy: Installed at "C:\Program Files (x86)\Chase Bliss Editor\kivy__init__.pyc"
> [INFO ] Python: v3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
> [INFO ] Python: Interpreter at "C:\Program Files (x86)\Chase Bliss Editor\Chase Bliss Editor.exe"
> [INFO ] Factory: 184 symbols loaded
> [INFO ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
> [INFO ] Window: Provider: sdl2
> [INFO ] GL: Using the "OpenGL" graphics system
> [INFO ] GL: GLEW initialization succeeded
> [INFO ] GL: Backend used
> [INFO ] GL: OpenGL version <b'4.6.0 NVIDIA 461.37'>
> [INFO ] GL: OpenGL vendor <b'NVIDIA Corporation'>
> [INFO ] GL: OpenGL renderer <b'GeForce RTX 2060/PCIe/SSE2'>
> [INFO ] GL: OpenGL parsed version: 4, 6
> [INFO ] GL: Shading version <b'4.60 NVIDIA'>
> [INFO ] GL: Texture max size <32768>
> [INFO ] GL: Texture max units <32>
> [INFO ] Window: auto add sdl2 input provider
> [INFO ] Window: virtual keyboard not allowed, single mode, not docked
> [INFO ] Text: Provider: sdl2
> [INFO ] GL: NPOT texture support is available
> [INFO ] GL: Unpack subimage support is available
> [WARNING] Both Window.minimum_width and Window.minimum_height must be bigger than 0 for the size restriction to take effect.
> [INFO ] Base: Start application main loop
> [INFO ] WindowSDL: exiting mainloop and closing.
> [INFO ] Base: Leaving application in progress...

Thanks for the heads up on this side - I took a look at the logs and realised (confirmed by checks using the open file feature) that the config file referenced hadn't been created.  A reinstall fixed that.  The logs indicated that it couldn't find the filepath for the user - although I installed under an administrator account, I'm guessing it was fussy about *which* administrator account...( maybe?)  The reinstall didn't fix but I was able to create a new config init patch config file afterwards.

**Comment by grendelmintcake** [comment] 2021-04-16 12:32
> On to the MIDI Issue:
> Save to Brother should send the current settings on the screen to the pedal. If the settings on the pedal and on the screen are similar you may not hear the difference. Note that when you change the settings on the screen, the settings on the pedal are changing real-time. To ensure "Send to Brothers" is working as expected, Set the knobs on the screen. The twist the knobs on the pedal to create a much different sound, the click send to brothers to hear the sound that is set on the screen.
> 
> Assuming you should be hearing the difference and are not, there could be an issue with the midi devices you are using or the way they are connected.
> 
> How are you connecting the pedal to the computer? Please include the devices and the cable types (TS or TRS).

**Comment by grendelmintcake** [comment] 2021-04-16 12:41
The 'Send to Brothers' and 'Save Preset to Brothers' options don't seem to affect the pedal with my current setup.  I've tested some PC# messages out with my MS3 and confirmed that the Brothers is listening on MIDI channel #2.  My hookup to the Brothers is via a USB-to-MIDI adaptor out of the PC, via a 5pin female-to-female DIN adaptor into a Disaster Area 5 Pin MIDI to Chase Bliss Cable.  The latter is TRS - link below:

https://www.disasterareadesigns.com/shop/p/5p-cba-midi-cable

The Disaster Area cable is definitely receiving and transmitting MIDI, this is what I've tested with the MS3-Brothers.

**Comment by ElliotGarbus** [comment] 2021-04-16 13:19
It is a possibility is that something corrupted the install of the app.  If you look at the log and see errors about a midi file, it could be a virus scanner is causing an issue – although these kinds of issues usually get reported as some kind of error.  It may be easiest to turn off your virus scanner, and reinstall the app, and see the result.  I wonder if the virus scanner blocked the creation of the ini file.

When you turn a knob on the screen is it effecting the pedal?
Do you have any inidicator leds on your usb to midi device that light up when midi traffic is sent?
Is the MIDI out on the USB to MIDI Cable connected to the MIDI to TRS cable?

Another possibility is the USB to MIDI adaptor.  What usb to 5-pin midi adaptor are you using.  While I would expect most would all work fine with this editor and the chase bilss pedals, I know that some will not work with the Meris pedals because they fail to pass SYSEX messages and have other limitations.  I’m wondering if a longer string of CC messages is causing a problem in the USB-to MIDI adaptor.  FWIW I use a Roland UM-One MkII.

**Comment by ElliotGarbus** [comment] 2021-10-16 14:15
I'm closing this issue.  If you still are having trouble feel free to reach out again.

**Closed as completed by ElliotGarbus** 2021-10-16 14:15 UTC
